spring:
  datasource:
    url: jdbc:mysql://localhost:3306/csspatternapp?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Europe/Warsaw&jdbcCompliantTruncation=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  liquibase:
    contexts: prod